AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  schx-job-viewer

  Sample SAM Template for schx-job-viewer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  ##########################################
  # S3 Bucket for Job Logs
  ##########################################
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: schx-job-view-test-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  ##########################################
  # DynamoDB Table - ScheduleX Job Metadata Table
  ##########################################
  ScheduleXJobMetadataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: schedulex-job-metadata
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: jobId
          AttributeType: S
        - AttributeName: companyName
          AttributeType: S
      KeySchema:
        - AttributeName: jobId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CompanyNameIndex
          KeySchema:
            - AttributeName: companyName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ##########################################
  # Create New Job Function
  ##########################################
  ScheduleXJobViewerAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/schedulex-job-viewer-api
      Handler: index.handler
      Runtime: nodejs22.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          SCHEDULEX_JOB_METADATA_TABLE_NAME: !Ref ScheduleXJobMetadataTable
          PROJECT_REGION: !Ref AWS::Region
          S3_BUCKET_NAME: !Ref S3Bucket
      Events:
        CreateNewJob:
          Type: Api
          Properties:
            Path: /create-new-job
            Method: put
        ListJobs:
          Type: Api
          Properties:
            Path: /list-jobs
            Method: get
        DownloadJobLogs:
          Type: Api
          Properties:
            Path: /download-job-logs
            Method: post
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref ScheduleXJobMetadataTable
      - S3CrudPolicy:
          BucketName: !Ref S3Bucket
      - Statement:
          Effect: Allow
          Action:
            - s3:PutObject
          Resource: !Sub "${S3Bucket.Arn}/*"

Outputs:
  # API Gateway endpoint URL
  ScheduleXJobViewerFunction:
    Description: "ScheduleX Job Viewer Lambda Function ARN"
    Value: !GetAtt ScheduleXJobViewerAPI.Arn
  ScheduleXJobViewerFunctionRole:
    Description: "Implicit IAM Role created for ScheduleX Job Viewer function"
    Value: !GetAtt ScheduleXJobViewerAPIRole.Arn
  ScheduleXJobMetadataTableName:
    Description: "Name of the DynamoDB table for job metadata"
    Value: !Ref ScheduleXJobMetadataTable
  ScheduleXJobMetadataTableArn:
    Description: "ARN of the DynamoDB table for job metadata"
    Value: !GetAtt ScheduleXJobMetadataTable.Arn
